## â–‘â–ˆâ–€â–€â–‘â–€â–ˆâ–€â–‘â–ˆâ–€â–ˆâ–‘â–ˆâ–€â–„â–‘â–ˆâ–€â–€â–‘â–ˆâ–‘â–ˆâ–‘â–€â–ˆâ–€â–‘â–ˆâ–€â–ˆ
## â–‘â–€â–€â–ˆâ–‘â–‘â–ˆâ–‘â–‘â–ˆâ–€â–ˆâ–‘â–ˆâ–€â–„â–‘â–€â–€â–ˆâ–‘â–ˆâ–€â–ˆâ–‘â–‘â–ˆâ–‘â–‘â–ˆâ–€â–€
## â–‘â–€â–€â–€â–‘â–‘â–€â–‘â–‘â–€â–‘â–€â–‘â–€â–‘â–€â–‘â–€â–€â–€â–‘â–€â–‘â–€â–‘â–€â–€â–€â–‘â–€â–‘â–‘
# set you color palette

palette = "catppuccin_mocha"

add_newline = true
format="""\
($directory)[î‚°](fg:green bg:surface1)\
($git_branch)[î‚°](fg:surface1)\
($line_break)\
($character)\
"""
right_format = """\
($git_commit)\
($git_status)\
($git_state)\
($jobs$status)\
[î‚²](fg:surface1)($cmd_duration)\
[î‚²](bg:surface1 fg:blue)($time)\
"""

[os]
disabled = false
style = "bg:green fg:mantle"
format = '[ $symbol]($style)'

[hostname]
format = '[ @$hostname ]($style)'
style = 'bold bg:surface1 fg:sapphire'
ssh_only = false

[shell]
disabled = true
bash_indicator = '\$_'
fish_indicator = "" # Empty string as Fish Shell is my default shell
# fish_indicator = "â‹–â‹—â‹–"
zsh_indicator = "%_"
powershell_indicator = "îšƒ" # nf-seti-powershell
ion_indicator = '(\$_)'
elvish_indicator = "ó°˜§" # nf-md-lambda
tcsh_indicator = "ó°‡¥ " # nf-md-duck
nu_indicator = "[ó°¥­](fg:color_base_green)" # nf-md-greater_than
xonsh_indicator = "ğŸš" # seashell emoji
cmd_indicator = "î¯„" # nf-cod-terminal_cmd
unknown_indicator = "ï™ " # nf-fa-question_circle
style = "bg:color_foreground_dark fg:color_foreground_light"
format = "[$indicator]($style)"

[character]
success_symbol = "[ ï” ](green)"
error_symbol = "[ ï” ](red)"
vimcmd_symbol = "[ ï“ ](blue)"
vimcmd_visual_symbol = "[ ï“ ](mauve)"
vimcmd_replace_symbol = "[ ï“ ](peach"
format = "$symbol"

[directory]
format = "[$read_only]($read_only_style)[ $path ]($style)"
style = 'bold bg:green fg:mantle'
read_only = " ï€£"
read_only_style = 'bold bg:green fg:mantle'
truncation_length = 6
truncation_symbol = '.../'
truncate_to_repo = false
use_os_path_sep = false
use_logical_path = true

[git_branch]
format = "([ ï˜ $branch ](bg:surface1 fg:teal))"

[git_commit]
format = '[$hash](yellow)'

[git_status]
# disabled = true
style = "yellow"
staged = "ï€Œ ${count}" # nf-fa-check
modified = " ï„ ${count}" # nf-fa-edit
# modified = " ï€ ${count}" # nf-fa-pencil
renamed = "ó°—§ ${count}" # nf-md-cursor_text
untracked = " ï„¨ ${count}]" # nf-fa-question
deleted = "[ ï€ ${count}](red)" # nf-fa-remove
conflicted = "ï€¤ ${count}" # nf-fa-flag
stashed = " ï†œ ${count}" # nf-fa-bank
# stashed = " ï€œ ${count}" # nf-fa-inbox
up_to_date = ""
ahead = "ó°™ ${count}" # nf-md-arrow_expand_up
behind = "ó°– ${count}" # nf-md-arrow_expand_down
diverged = "ó°¡ ${ahead_count} ${behind_count}" # nf-md-arrow_expand_vertical
# diverged = "ó°¯ ${ahead_count} ${behind_count}" # nf-md-swap_vertical_bold
# ignore_submodules = true
format = "[($staged$modified$renamed$untracked$deleted$conflicted$stashed$ahead_behind )]($style)"

[git_state]
format = '[$state($progress_current/$progress_total)](yellow)'

[line_break] 
disabled = false

[time]
format = '[ ïº $time ](bold bg:blue fg:mantle)'
disabled = false
time_format = '%H:%M'

[cmd_duration]
format = '[ $duration  ](bg:surface1 fg:teal)'
min_time = 1
show_milliseconds = true
disabled = false

[status]
format = '[$status(:$common_meaning)(:$signal_name)](pink)'
disabled = false

[jobs]
format = '[$symbol $number](yellow)'
symbol = 'âš™'
symbol_threshold = 1
number_threshold = 1

[os.symbols]
Alpaquita = "ïƒ³ "
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "îœ "
Arch = "ïŒƒ "
Artix = "ïŒŸ " 
CentOS = "ïŒ„ " 
Debian = "ïŒ† "
DragonFly = "îŠ " 
Emscripten = "ïˆ… " 
EndeavourOS = "ïŒ¢ " 
Fedora = "ïŒŠ " 
FreeBSD = "ïŒŒ " 
Garuda = "ó°›“ " 
Gentoo = "ïŒ " 
HardenedBSD = "ó°”‡  " 
Illumos = "ïŒ¦ " 
Linux = "ïŒš " 
Mabox = "ó°†¦  " 
Macos = "ïŒ‚ " 
Manjaro = "ïŒ’ " 
Mariner = "ï‡ " 
MidnightBSD = "ï†† "
Mint = "ó°£­  "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ïŒ¨ "
OpenCloudOS = "ïƒ‚ " 
openEuler = "ó°’  " 
openSUSE = "ïŒ” " 
OracleLinux = "ó°Œ·  " 
Pop = "ïŒª " 
Raspbian = "ïŒ• " 
Redhat = "ó±„› " 
RedHatEnterprise = "ïŒ– "
Redox = "ó°€˜  "
Solus = "ïŒ­ " 
SUSE = "ïŒ” " 
Ubuntu = "ïŒ› "
Unknown = "ï™ " 
Windows = "ï…º "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

